url_shortener/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from shorten_app.views import IndexView, AllClick, redirect, AllLink, CreateLink, EditLink

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^all/$', AllClick.as_view(), name="all_clicks"),
    url(r'^links/$', AllLink.as_view(), name="all_links"),
    url(r'^accounts/login/$', auth_views.login, name="login"),
    url(r'^accounts/logout/$', auth_views.logout, name="logout"),
    url(r'^create_link/$', CreateLink.as_view(), name="create_link"),
    url(r'^edit/(?P<pk>\w+)', EditLink.as_view(), name="edit_urls"),
    url(r'^(?P<captured_id>\w+)', redirect, name="clicky")
]

shorten_app/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Url(models.Model):
    url = models.URLField()
    title = models.CharField(max_length=100)
    description = models.TextField()
    short_version = models.CharField(max_length=30)
    added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.url

    class Meta:
        ordering = ["-added"]


class Clicks(models.Model):
    time_of_click = models.DateTimeField(auto_now_add=True)
    referenced_url = models.ForeignKey(Url)

    class Meta:
        ordering = ["-time_of_click"]

shorten_app/forms.py
from django import forms
from shorten_app.models import Url


class UrlForm(forms.ModelForm):

    class Meta:
        model = Url
        exclude = ['short_version']

shorten_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from hashids import Hashids
# Create your views here.
from django.views.generic import View, CreateView, ListView, UpdateView
from django.core.urlresolvers import reverse
from shorten_app.forms import UrlForm
from shorten_app.models import Url, Clicks


class IndexView(View):
    def get(self, request):
        last_url = Url.objects.first()
        if self.request.user.id:
            user_urls = Url.objects.filter(user=self.request.user)
            return render(request, 'index.html', {'last_url': last_url,
                                                  'user_urls': user_urls
                                                  }
                          )
        else:
            return render(request, 'index.html', {'last_url': last_url})


class AllClick(ListView):
    model = Clicks


class AllLink(ListView):
    model = Url


class CreateLink(CreateView):
    model = Url
    fields = ('url', 'title', 'description')

    def form_valid(self, form):
        url_object = form.save(commit=False)
        url_object.user = self.request.user
        url_object.save()
        print(url_object.id)
        hashids = Hashids(min_length=5)
        hashid = hashids.encode(url_object.id)
        url_object.short_version = hashid
        url_object.save()
        print(url_object.short_version)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('index')


class EditLink(UpdateView):
    model = Url
    fields = ('url', 'title', 'description')


def redirect(request, captured_id):
    redirect_url_object = Url.objects.get(short_version=captured_id)
    redirect_url = redirect_url_object.url

    Clicks.objects.create(referenced_url=redirect_url_object)

    return HttpResponseRedirect(redirect_url)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <ul class="nav nav-pills">
            <li role="presentation" class="active"><a href="{% url 'index' %}">Home</a></li>
            <li role="presentation"><a href="{% url 'all_clicks' %}">All Clicks</a></li>
            <li role="presentation"><a href="{% url 'all_links' %}">All Bookmarks</a></li>
            <li role="presentation"><a href="{% url 'create_link' %}">Add New Bookmark</a></li>
            {% if request.user.is_authenticated %}
                <li role="presentation"><a href="{% url 'logout' %}">Log Out {{ request.user }}</a></li>
            {% else %}
                <li role="presentation"><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
        </ul>

<div class="container">{% block content %}{% endblock %}</div>

</div>
<script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    {% if request.user.is_authenticated %}
    <h3>Welcome {{ request.user }}. Your Bookmarks:</h3>
    {% for url in user_urls %}
        <div class="panel panel-default">
            <div class="panel-body">
                <div>
                    <h4>
                        <div>
                            <a href="{% url 'edit_urls' url.pk %}">Edit Bookmark</a>
                        </div>
                    </h4>
                    <h4>
                        <div>
                            <a href="{% url 'clicky' url.short_version %}">{{ url.short_version }}</a>
                        </div>
                    </h4>
                </div>
                <div>
                    <h4>{{ url.title }}: <a href="{{ url.url }}"> {{ url.url }} </a></h4>
                    <div>{{ url.description }}</div>
                    <div><h6>Created: {{ url.added }} {{ url.clicks_set.count }} Total Clicks</h6></div>
                </div>
            </div>
        </div>

    {% endfor %}
    {% else %}
    <h3>Welcome! <a href="{% url 'login' %}">Login to start creating Bookmarks</a></h3>
    {% endif %}

    <div><h3>Latest Bookmark: {{ last_url.title }}</h3></div>
    <div><h3>Link: <a href="{% url 'clicky' last_url.short_version %}">{{ last_url.short_version }}</a></h3></div>
</div>
{% endblock %}

templates/shorten_app/clicks_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <h2>All Clicks</h2>
    {% for entry in clicks_list %}
        <div class="panel panel-default">
            <div class="panel-body">
                <h4>{{ entry.time_of_click }} <a href="{% url 'clicky' entry.referenced_url.short_version %}">/{{ entry.referenced_url.short_version }}</a></h4>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/shorten_app/url_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    {% if request.user.is_authenticated %}
    <div><h2>Create or Edit a Bookmark:</h2></div>
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="submit">
        </form>
    </div>
    {% else %}
        <h2>Log in to start making bookmarks!</h2>
    {% endif %}
    </div>
{% endblock %}

templates/shorten_app/url_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <h2>All saved Urls</h2>
    {% for url in url_list %}
        <div class="panel panel-default">
            <div class="panel-body">
                <div>
                    <h4><a href="{% url 'clicky' url.short_version %}">{{ url.short_version }}</a></h4>
                </div>
                <div>
                    <h4>{{ url.title }}: <a href="{{ url.url }}"> {{ url.url }} </a></h4>
                    <div>{{ url.description }}</div>
                    <div><h6>Created: {{ url.added }} {{ url.clicks_set.count }} Total Clicks</h6></div>
                </div>
            </div>
        </div>

    {% endfor %}
    </div>
{% endblock %}